import type { PoolClient } from "pg";

export type ImportJobPhase = "uploaded" | "mapped" | "validated" | "committing" | "committed" | "failed";

export interface ImportJobRecord {
  id: string;
  tenantId: string;
  createdByCollegeUserId: string;
  originalFilename: string;
  filePath: string;
  fileSha256: string;
  columnMapping: Record<string, string>;
  phase: ImportJobPhase;
  rowCount: number | null;
  validCount: number | null;
  invalidCount: number | null;
  createCount: number | null;
  updateCount: number | null;
  committedRowCount: number | null;
  committedAt: Date | null;
  errorMessage: string | null;
  createdAt: Date;
  updatedAt: Date;
}

interface ImportJobRow {
  id: string;
  tenant_id: string;
  created_by_college_user_id: string;
  original_filename: string;
  file_path: string;
  file_sha256: string;
  column_mapping: Record<string, string>;
  phase: ImportJobPhase;
  row_count: number | null;
  valid_count: number | null;
  invalid_count: number | null;
  create_count: number | null;
  update_count: number | null;
  committed_row_count: number | null;
  committed_at: Date | null;
  error_message: string | null;
  created_at: Date;
  updated_at: Date;
}

const SELECT_COLUMNS = `
  id, tenant_id, created_by_college_user_id, original_filename, file_path, file_sha256,
  column_mapping, phase, row_count, valid_count, invalid_count, create_count, update_count,
  committed_row_count, committed_at, error_message, created_at, updated_at
`;

function mapRow(row: ImportJobRow): ImportJobRecord {
  return {
    id: row.id,
    tenantId: row.tenant_id,
    createdByCollegeUserId: row.created_by_college_user_id,
    originalFilename: row.original_filename,
    filePath: row.file_path,
    fileSha256: row.file_sha256,
    columnMapping: row.column_mapping,
    phase: row.phase,
    rowCount: row.row_count,
    validCount: row.valid_count,
    invalidCount: row.invalid_count,
    createCount: row.create_count,
    updateCount: row.update_count,
    committedRowCount: row.committed_row_count,
    committedAt: row.committed_at,
    errorMessage: row.error_message,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
  };
}

export interface CreateImportJobParams {
  /** Generated by the caller before this insert, since the storage path (tenantId/id.ext) is written first -- same pattern as colleges.ts's tenant creation. */
  id: string;
  tenantId: string;
  createdByCollegeUserId: string;
  originalFilename: string;
  filePath: string;
  fileSha256: string;
  columnMapping: Record<string, string>;
}

export async function createImportJob(client: PoolClient, params: CreateImportJobParams): Promise<ImportJobRecord> {
  const result = await client.query<ImportJobRow>(
    `insert into public.import_jobs
       (id, tenant_id, created_by_college_user_id, original_filename, file_path, file_sha256, column_mapping)
     values ($1, $2, $3, $4, $5, $6, $7)
     returning ${SELECT_COLUMNS}`,
    [
      params.id,
      params.tenantId,
      params.createdByCollegeUserId,
      params.originalFilename,
      params.filePath,
      params.fileSha256,
      params.columnMapping,
    ],
  );
  return mapRow(result.rows[0]);
}

export async function findImportJobById(client: PoolClient, id: string): Promise<ImportJobRecord | null> {
  const result = await client.query<ImportJobRow>(`select ${SELECT_COLUMNS} from public.import_jobs where id = $1`, [
    id,
  ]);
  return result.rows[0] ? mapRow(result.rows[0]) : null;
}

/** Informational-only duplicate-upload warning (spec 8.3) -- never blocks a re-upload. */
export async function findImportJobsByFileHash(client: PoolClient, fileSha256: string): Promise<ImportJobRecord[]> {
  const result = await client.query<ImportJobRow>(
    `select ${SELECT_COLUMNS} from public.import_jobs where file_sha256 = $1 order by created_at desc`,
    [fileSha256],
  );
  return result.rows.map(mapRow);
}

export async function setImportJobMapping(
  client: PoolClient,
  id: string,
  columnMapping: Record<string, string>,
): Promise<void> {
  await client.query(
    `update public.import_jobs set column_mapping = $2, phase = 'mapped', updated_at = now() where id = $1`,
    [id, columnMapping],
  );
}

export interface ImportJobValidationResult {
  rowCount: number;
  validCount: number;
  invalidCount: number;
  createCount: number;
  updateCount: number;
}

export async function setImportJobValidationResult(
  client: PoolClient,
  id: string,
  result: ImportJobValidationResult,
): Promise<void> {
  await client.query(
    `update public.import_jobs
     set phase = 'validated', row_count = $2, valid_count = $3, invalid_count = $4,
         create_count = $5, update_count = $6, updated_at = now()
     where id = $1`,
    [id, result.rowCount, result.validCount, result.invalidCount, result.createCount, result.updateCount],
  );
}

export interface SetImportJobPhaseOptions {
  errorMessage?: string | null;
  committedRowCount?: number;
}

/** Used by the worker's commit job to move through committing -> committed/failed. */
export async function setImportJobPhase(
  client: PoolClient,
  id: string,
  phase: ImportJobPhase,
  options: SetImportJobPhaseOptions = {},
): Promise<void> {
  await client.query(
    `update public.import_jobs
     set phase = $2,
         error_message = coalesce($3, error_message),
         committed_row_count = coalesce($4, committed_row_count),
         committed_at = case when $2 = 'committed' then now() else committed_at end,
         updated_at = now()
     where id = $1`,
    [id, phase, options.errorMessage ?? null, options.committedRowCount ?? null],
  );
}
